In [1]:
''' Example1'''

' Example1'

In [1]:
import numpy as np
empty_array = np.empty(2, dtype=int)

In [2]:
zeros_array = np.zeros(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


In [3]:
arange_array = np.arange(0, 10)
print(arange_array)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
eye_matrix = np.eye(3)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
randint_array = np.random.randint(1, 10,(3, 3))
print(randint_array)

[[7 8 2]
 [8 3 4]
 [8 9 8]]


In [6]:
rand_array = np.random.rand(2, 3)
print(rand_array)

[[0.6976067  0.29410662 0.4657553 ]
 [0.53964385 0.42081443 0.38239881]]


In [13]:
'''Example2: '''

'Example2: '

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("arr :", arr)
print("Shape of arr:", arr.shape)
print("Size of arr:", arr.size)
print("Data type of arr :", arr.dtype)
print("Number of dimensions of arr:", arr.ndim)

arr : [1 2 3 4 5]
Shape of arr: (5,)
Size of arr: 5
Data type of arr : int64
Number of dimensions of arr: 1


In [16]:
'''Example 3'''

'Example 3'

In [ ]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5])
first_element = arr1d[0]
print("The first element of arr1d: ", first_element)
last_element = arr1d[-1]
print("The last element of arr1d: ", last_element)

The first element of arr1d:  1
The last element of arr1d:  5


In [18]:
'''Example 4'''

'Example 4'

In [ ]:
import numpy as np

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)
element_1_2 = arr2d[0, 1]
print(element_1_2)

[[1 2 3]
 [4 5 6]]
2


Example 5

In [ ]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5])
slice_arr1d = arr1d[1:4]
print("arr1d:", arr1d)
print("Sclicing arr1d frome 1 to 3:", slice_arr1d)

arr1d: [1 2 3 4 5]
Sclicing arr1d frome 1 to 3: [2 3 4]


In [ ]:
import numpy as np

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
slice_arr2d = arr2d[1:3, 1:]
print("arr2d:\n", arr2d)
print("Slicing arr2d from row 2 to row 3 and column 2 to column end:\n", slice_arr2d)

arr2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Slicing arr2d from row 2 to row 3 and column 2 to column end:
 [[5 6]
 [8 9]]


Example 7

In [ ]:
import numpy as np

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
new_array = original_array.transpose()
print(new_array)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Example 8

In [ ]:
import numpy as np

original_array = np.array([[0, 1], [2, 3], [4, 5]])
new_array = np.reshape(original_array, (2, 3))
print(new_array)

[[0 1 2]
 [3 4 5]]


Example 9

In [ ]:
import numpy as np

arr_2D = np.array([[1, 2, 3], [4, 5, 6]])
# (2, 3) ->(3, 2)
new_arr_2D = np.reshape(arr_2D, (3, 2))
# 2D -> 1D
arr_1D = np.reshape(arr_2D, newshape=(6,))
print("array 2D:\n", arr_2D, arr_2D.shape)
print("new array 2D :\n", new_arr_2D, new_arr_2D.shape)
print("array 1D:\n", arr_1D, arr_1D.shape)

array 2D:
 [[1 2 3]
 [4 5 6]] (2, 3)
new array 2D :
 [[1 2]
 [3 4]
 [5 6]] (3, 2)
array 1D:
 [1 2 3 4 5 6] (6,)


Example 10

In [ ]:
import numpy as np

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
original_array.resize(3, 4)
print(original_array)

[[1 2 3 4]
 [5 6 7 8]
 [9 0 0 0]]


Example 11

In [ ]:
import numpy as np

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
new_array1 = np.insert(original_array, 0, [10, 10, 10], axis=0)
print(new_array1)
new_array2 = np.insert(original_array, 3, [10, 10, 10], axis=0)
print(new_array2)
new_array3 = np.insert(original_array, 0, [10, 10, 10], axis=1)
print(new_array3)
new_array4 = np.insert(original_array, 3, [10, 10, 10], axis=1)
print(new_array4)

[[10 10 10]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 10 10]]
[[10  1  2  3]
 [10  4  5  6]
 [10  7  8  9]]
[[ 1  2  3 10]
 [ 4  5  6 10]
 [ 7  8  9 10]]


Example 12

In [ ]:
import numpy as np

original_array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
original_array2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
new_array1 = np.append(original_array1, original_array2, axis=1)
print(new_array1)
new_array2 = np.append(original_array1, original_array2, axis=0)
print(new_array2)

[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]
 [ 7  8  9 70 80 90]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]
 [40 50 60]
 [70 80 90]]


Example 13

In [ ]:
import numpy as np

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
new_array1 = np.delete(original_array, 0, axis=0)
print(new_array1)
new_array2 = np.delete(original_array, 0, axis=1)
print(new_array2)
new_array3 = np.delete(original_array, 2, axis=0)
print(new_array3)
new_array4 = np.delete(original_array, 2, axis=1)
print(new_array4)

[[4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]
 [7 8]]


Example 14

In [ ]:
import numpy as np

# Tạo mảng a
a = np.array(
    [
        [0, 1, 3],
        [5, 7, 9],
    ]
)

# Tạo mảng b
b = np.array([[0, 2, 4], [6, 8, 10]])

print("Array a:\n", a)
print("\nArray b:\n", b)

# 1. concatenate theo axis=1
concat_axis1 = np.concatenate((a, b), axis=1)
print("\nnp.concatenate((a, b), axis=1):\n", concat_axis1)

# 2. hstack (nối theo chiều ngang → giống axis=1)
hstack_arr = np.hstack((a, b))
print("\nnp.hstack((a, b)):\n", hstack_arr)

# 3. vstack (nối theo chiều dọc → giống axis=0)
vstack_arr = np.vstack((a, b))
print("\nnp.vstack((a, b)):\n", vstack_arr)

Array a:
 [[0 1 3]
 [5 7 9]]

Array b:
 [[ 0  2  4]
 [ 6  8 10]]

np.concatenate((a, b), axis=1):
 [[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]

np.hstack((a, b)):
 [[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]

np.vstack((a, b)):
 [[ 0  1  3]
 [ 5  7  9]
 [ 0  2  4]
 [ 6  8 10]]


Example 15

In [ ]:
import numpy as np

arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
arr_3 = np.hstack((arr_1, arr_2))
print("arr 1:\n", arr_1)
print("arr 2:\n", arr_2)
print("Result_arr:\n", arr_3)

arr 1:
 [1 2 3]
arr 2:
 [4 5 6]
Result_arr:
 [1 2 3 4 5 6]


Example 16

In [ ]:
import numpy as np

arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])
arr_3 = np.vstack((arr_1, arr_2))
print("arr 1:", arr_1)
print("arr 2:", arr_2)
print("Result_arr:\n", arr_3)

arr 1: [1 2 3]
arr 2: [4 5 6]
Result_arr:
 [[1 2 3]
 [4 5 6]]


Example 17

In [ ]:
import numpy as np

arr_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2 = np.array([[7, 8, 9], [10, 11, 12]])
arr_3 = np.concatenate((arr_1, arr_2), axis=0)
arr_4 = np.concatenate((arr_1, arr_2), axis=1)
print("Array 1:\n", arr_1)
print("Array 2:\n", arr_2)
print("Result( axis=0) :\n", arr_3)
print("Result( axis=1) :\n", arr_4)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Result( axis=0) :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Result( axis=1) :
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Example 18

In [ ]:
import numpy as np

# array 1D
arr_1 = np.array([1, 2, 3])
# 1D -> 2D
arr_2 = arr_1[np.newaxis, :]
# 2D -> 5D
arr_3 = arr_2[np.newaxis, :, np.newaxis, :, np.newaxis]
print("array 1: ", arr_1, arr_1.shape)
print("array 2: ", arr_2, arr_2.shape)
print("array 3:\n ", arr_3, arr_3.shape)

array 1:  [1 2 3] (3,)
array 2:  [[1 2 3]] (1, 3)
array 3:
  [[[[[1]
    [2]
    [3]]]]] (1, 1, 1, 3, 1)


Example 19

In [ ]:
import numpy as np

arr_1 = np.array([1, 2, 3])
# 1D -> 2D
arr_2 = np.expand_dims(arr_1, axis=0)
# 2D -> 5D
arr_3 = np.expand_dims(arr_2, axis=(0, 2, 4))
print("array 1:", arr_1, arr_1.shape)
print("array 2:", arr_2, arr_2.shape)
print("array 3:\n", arr_3, arr_3.shape)

array 1: [1 2 3] (3,)
array 2: [[1 2 3]] (1, 3)
array 3:
 [[[[[1]
    [2]
    [3]]]]] (1, 1, 1, 3, 1)


Example 20

In [18]:
import numpy as np

arr2d = np.array([[1, 7, 3], [10, 8, 6], [5, 15, 9]])
print("Original array\n", arr2d)
sort_in_row = np.sort(arr2d, axis=1)
sort_in_col = np.sort(arr2d, axis=0)
print("Result by row:\n", sort_in_row)
print("Result by col:\n", sort_in_col)

Original array
 [[ 1  7  3]
 [10  8  6]
 [ 5 15  9]]
Result by row:
 [[ 1  3  7]
 [ 6  8 10]
 [ 5  9 15]]
Result by col:
 [[ 1  7  3]
 [ 5  8  6]
 [10 15  9]]


Example 21

In [17]:
import numpy as np

# Mảng a (3×3)
a = np.array([[0, 3, 1], [3, 7, 5], [6, 4, 8]])

# Mảng b (1×3) → sẽ được broadcast cho phù hợp với a
b = np.array([10, 5, 11])

print("Array a:\n", a)
print("\nArray b:\n", b)

# 1. Add
add_result = np.add(a, b)
print("\nnp.add(a, b):\n", add_result)

# 2. Subtract
sub_result = np.subtract(a, b)
print("\nnp.subtract(a, b):\n", sub_result)

# 3. Multiply
mul_result = np.multiply(a, b)
print("\nnp.multiply(a, b):\n", mul_result)

# 4. Divide
div_result = np.divide(a, b)
print("\nnp.divide(a, b):\n", div_result)

Array a:
 [[0 3 1]
 [3 7 5]
 [6 4 8]]

Array b:
 [10  5 11]

np.add(a, b):
 [[10  8 12]
 [13 12 16]
 [16  9 19]]

np.subtract(a, b):
 [[-10  -2 -10]
 [ -7   2  -6]
 [ -4  -1  -3]]

np.multiply(a, b):
 [[ 0 15 11]
 [30 35 55]
 [60 20 88]]

np.divide(a, b):
 [[0.         0.6        0.09090909]
 [0.3        1.4        0.45454545]
 [0.6        0.8        0.72727273]]


Example 22

In [ ]:
import numpy as np

a = np.array([[0, 3, 1], [3, 7, 5], [6, 4, 8]])
b = [10, 5, 11]
print("add_array =\n", np.add(a, b))
print("subtract_array =\n", np.subtract(a, b))
print("multiply_array =\n", np.multiply(a, b))
print("divide_array =\n", np.divide(a, b))

add_array =
 [[10  8 12]
 [13 12 16]
 [16  9 19]]
subtract_array =
 [[-10  -2 -10]
 [ -7   2  -6]
 [ -4  -1  -3]]
multiply_array =
 [[ 0 15 11]
 [30 35 55]
 [60 20 88]]
divide_array =
 [[0.         0.6        0.09090909]
 [0.3        1.4        0.45454545]
 [0.6        0.8        0.72727273]]


Example 23

In [ ]:
import numpy as np

# Mảng a và b theo slide
a = np.array([7, 3, 4, 5, 1])
b = np.array([3, 4, 5, 6, 7])

print("Array a:", a)
print("Array b:", b)

# 1. remainder (giống mod)
rem = np.remainder(a, b)
print("\nnp.remainder(a, b):", rem)

# 2. mod (giống remainder)
mod = np.mod(a, b)
print("np.mod(a, b):", mod)

# 3. power
power = np.power(a, b)
print("\nnp.power(a, b):", power)

# 4. reciprocal
reciprocal = np.reciprocal(a)  # 1/a nhưng giá trị integer sẽ làm tròn về 0
print("np.reciprocal(a):", reciprocal)

Array a: [7 3 4 5 1]
Array b: [3 4 5 6 7]

np.remainder(a, b): [1 3 4 5 1]
np.mod(a, b): [1 3 4 5 1]

np.power(a, b): [  343    81  1024 15625     1]
np.reciprocal(a): [0 0 0 0 1]


Example 24

In [ ]:
import numpy as np

a = np.array([[0, 3, 1], [3, 7, 5], [6, 4, 8]])
b = [10, 5, 10]
print("Sum_a =", np.sum(a))
print("Sum_b =", np.sum(b))
print("Sum_a_axis_0 =", np.sum(a, axis=0))
print("Sum_a_axis_1 =", np.sum(a, axis=1))

Sum_a = 37
Sum_b = 25
Sum_a_axis_0 = [ 9 14 14]
Sum_a_axis_1 = [ 4 15 18]


Example 25

In [ ]:
import numpy as np

a = np.array([[0, 3, 1], [3, 7, 5], [6, 4, 8]])
b = [10, 5, 11]
print("Sum_a =", np.sum(a))
print("Sum_b =", np.sum(b))
print("Sum_a_axis_0 =", np.sum(a, axis=0))
print("Sum_a_axis_1 =", np.sum(a, axis=1))

Sum_a = 37
Sum_b = 26
Sum_a_axis_0 = [ 9 14 14]
Sum_a_axis_1 = [ 4 15 18]


Example 26

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
max_value = np.max(arr)
print("largest value :", max_value)
min_value = np.min(arr)
print("Smallest value:", min_value)

largest value : 5
Smallest value: 1


Example 27

In [ ]:
import numpy as np

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
max_value_row = np.max(arr2d, axis=1)
max_value_col = np.max(arr2d, axis=0)
print("Maximum value in row:", max_value_row)
print("Maximum value in col:", max_value_col)
min_value_row = np.min(arr2d, axis=1)
min_value_col = np.min(arr2d, axis=0)
print("Minimum value in row:", min_value_row)
print("Minimum value in col:", min_value_col)

Maximum value in row: [3 6]
Maximum value in col: [4 5 6]
Minimum value in row: [1 4]
Minimum value in col: [1 2 3]


Example 28

In [ ]:
import numpy as np

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
max_value_row = np.max(arr2d, axis=1)
max_index_row = np.argmax(arr2d, axis=1)
print("Maximum value in row:", max_value_row)
print("Index:", max_index_row)
max_value_col = np.max(arr2d, axis=0)
max_index_col = np.argmax(arr2d, axis=0)
print("Maximum value in col:", max_value_col)
print("Index:", max_index_col)

Maximum value in row: [3 6]
Index: [2 2]
Maximum value in col: [4 5 6]
Index: [1 1 1]


Example 29

In [ ]:
a = np.array([[0, 3, 1], [3, 7, 5], [6, 4, 8]])
b = np.array([10, 5, 11])

np.median(a)
np.median(b)
np.median(a, axis=0)
np.median(a, axis=1)

array([1., 5., 6.])

Example 30

In [ ]:
import numpy as np

a = np.array([[0, 3, 1], [3, 7, 5], [6, 4, 8]])
b = [10, 5, 11]
print("Median value in row:", np.median(a, axis=1))
print("Median value in col:", np.median(a, axis=0))
print("Median array A:", np.median(a))
print("Median array B:", np.median(b))

Median value in row: [1. 5. 6.]
Median value in col: [3. 4. 5.]
Median array A: 4.0
Median array B: 10.0


Example 31

In [ ]:
a = np.array([[0, 3, 1], [3, 7, 5], [6, 4, 8]])
b = np.array([10, 5, 11])

np.mean(a)
np.mean(b)
np.mean(a, axis=0)
np.mean(a, axis=1)

array([1.33333333, 5.        , 6.        ])

Example 32

In [ ]:
import numpy as np

a = np.array([[0, 3, 1], [3, 7, 5], [6, 4, 8]])
b = [10, 5, 11]
print("Mean_a =", np.mean(a))
print("Mean_b =", np.mean(b))
print("Mean_a_axis_0 =", np.mean(a, axis=0))
print("Mean_a_axis_1 =", np.mean(a, axis=1))

Mean_a = 4.111111111111111
Mean_b = 8.666666666666666
Mean_a_axis_0 = [3.         4.66666667 4.66666667]
Mean_a_axis_1 = [1.33333333 5.         6.        ]


Example 33

In [ ]:
import numpy as np

a = np.array([[4, 12, 0, 4], [6, 11, 8, 4], [18, 14, 13, 7]])

np.std(a, axis=0)
np.std(a, axis=1)
np.var(a, axis=0)
np.var(a, axis=1)

array([19.    ,  6.6875, 15.5   ])

Example 34

In [ ]:
import numpy as np

a = np.array([[4, 12, 0, 4], [6, 11, 8, 4], [18, 14, 13, 7]])
print("Standard Deviation_a_axis_0 =", np.std(a, axis=0))
print("Standard Deviation_a_axis_1 =", np.std(a, axis=1))
print("Variance_a_axis_0 =", np.var(a, axis=0))
print("Variance_a_axis_1 =", np.var(a, axis=1))

Standard Deviation_a_axis_0 = [6.18241233 1.24721913 5.35412613 1.41421356]
Standard Deviation_a_axis_1 = [4.35889894 2.58602011 3.93700394]
Variance_a_axis_0 = [38.22222222  1.55555556 28.66666667  2.        ]
Variance_a_axis_1 = [19.      6.6875 15.5   ]


Example 35

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = np.where(arr > 2)
print("Position of elements greater than 2:", result)
print("The value of the elements at the found position:", arr[result])

Position of elements greater than 2: (array([2, 3, 4]),)
The value of the elements at the found position: [3 4 5]


Example 36

In [ ]:
import numpy as np

a = np.array([[1, 0], [0, 1]])
b = np.array([[4, 1], [2, 2]])
print("Dot_Result =\n", np.dot(a, b))
print("Vdot_Result =\n", np.vdot(a, b))
print("Inner_Result =\n", np.inner(a, b))
print("Outer_Result =\n", np.outer(a, b))

Dot_Result =
 [[4 1]
 [2 2]]
Vdot_Result =
 6
Inner_Result =
 [[4 2]
 [1 2]]
Outer_Result =
 [[4 1 2 2]
 [0 0 0 0]
 [0 0 0 0]
 [4 1 2 2]]


Example 37

In [ ]:
import numpy as np

arr_1 = np.array([[1, 2], [3, 4]])
arr_2 = np.array([[5, 6], [7, 8]])
print("arr_1 :\n", arr_1)
print("arr_2 :\n", arr_2)
result_matmul = np.matmul(arr_1, arr_2)
print("Result:\n", result_matmul)

arr_1 :
 [[1 2]
 [3 4]]
arr_2 :
 [[5 6]
 [7 8]]
Result:
 [[19 22]
 [43 50]]


Example 38

In [ ]:
import math


def Euclicdean_distance(point1, point2):
    return math.sqrt((point1[0] - point2[0]) ** 2 + point1[1] - point2[1]) ** 2


point1 = (1, 2)
point2 = (4, 6)
distance = Euclicdean_distance(point1, point2)
print("Euclicdean distance:", distance)

Euclicdean distance: 5.000000000000001


In [ ]:
import numpy as np


def Euclicdean_distance_np(point1, point2):
    return np.linalg.norm(np.array(point1) - np.array(point2))


point1 = (1, 2)
point2 = (4, 6)
distance = Euclicdean_distance_np(point1, point2)
print("Euclicdean distance (NumPy):", distance)

Euclicdean distance (NumPy): 5.0


Example 39

In [ ]:
def manhattan_distance(point1, point2):
    return sum(abs(a - b) for a, b in zip(point1, point2))


point1 = (1, 2)
point2 = (4, 6)
distance = manhattan_distance(point1, point2)
print("Manhattan distance:", distance)

Manhattan distance: 7


In [ ]:
import numpy as np


def manhattan_distance_np(point1, point2):
    return np.sum(np.abs(np.array(point1) - np.array(point2)))


point1 = (1, 2)
point2 = (4, 6)
distance = manhattan_distance_np(point1, point2)
print("Manhattan distance (NumPy):", distance)

Manhattan distance (NumPy): 7


Example 40

In [ ]:
import numpy as np
import numpy.matlib

# with the specified shape and type without initializing entries
mat_e = np.matlib.empty((3, 2), dtype=int)
# filled with 0
mat_zeros = np.matlib.zeros(5, 3)
# filled with 1
mat_ones = np.matlib.ones(4, 3)
# diagonal elements filled with 1, others with 0
mat_ones = np.matlib.eye(3, 5)
# create square matrix with 0, diagonal filled with 1, others with 0
mat_zeros = np.matlib.identity(5)
# filled with random data
mat_e = np.matlib.empty(3, 2)

Example 41

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
np.save("out.npy", a)
b = np.load("out.npy")
print(b)

[1 2 3 4 5]


Example 42

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
np.savetxt("out.txt", a)
b = np.loadtxt("out.txt")
print(b)

[1. 2. 3. 4. 5.]


1. Explain the meaning of each command line and show the result of the
following code

In [16]:
import numpy as np  # Import thư viện NumPy để làm việc với mảng

a = np.array([1, 2, 3])  # Tạo mảng 1 chiều (vector) chứa các phần tử 1, 2, 3
print(type(a))  # In ra kiểu dữ liệu của biến a (numpy.ndarray)
print(a.shape)  # In kích thước của mảng a: (3,) nghĩa là có 3 phần tử
print(a[0], a[1], a[2])  # Truy cập và in ra từng phần tử trong mảng a theo chỉ số

a[0] = 5  # Thay đổi phần tử đầu tiên của mảng a từ 1 thành 5
print(a)  # In lại mảng a sau khi đã thay đổi

b = np.array([[1, 2, 3], [4, 5, 6]])  # Tạo mảng 2 chiều (ma trận 2x3)
print(b.shape)  # In kích thước của mảng b: (2, 3) → 2 hàng, 3 cột
print(b[0, 0], b[0, 1], b[1, 0])  # Truy cập các phần tử của ma trận:
# b[0,0] = 1 (hàng 1, cột 1)
# b[0,1] = 2 (hàng 1, cột 2)
# b[1,0] = 4 (hàng 2, cột 1)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


2. Explain the meaning of each command line and show the result of the
following code

In [15]:
import numpy as np

a = np.zeros((2, 2))  # Tạo mảng 2x2 toàn số 0
b = np.ones((1, 2))  # Tạo mảng 1x2 toàn số 1
c = np.full((2, 2), 7)  # Tạo mảng 2x2 với tất cả phần tử bằng 7
d = np.eye(2)  # Tạo ma trận 2x2 đơn vị (đường chéo chính = 1, còn lại = 0)
e = np.random.random(
    (2, 2)
)  # Tạo mảng 2x2 với các số thực ngẫu nhiên trong khoảng [0,1)

print("a:\n", a)
print("b:\n", b)
print("c:\n", c)
print("d:\n", d)
print("e:\n", e)

a:
 [[0. 0.]
 [0. 0.]]
b:
 [[1. 1.]]
c:
 [[7 7]
 [7 7]]
d:
 [[1. 0.]
 [0. 1.]]
e:
 [[0.96807958 0.68192286]
 [0.5415875  0.40671537]]


3. Explain the meaning of each command line and show the result of the
following code

In [14]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])  # Tạo mảng 3x4
b = a[
    :2, 1:3
]  # Lấy lát cắt (slice) gồm 2 hàng đầu tiên và cột 1 đến 2 (không bao gồm cột 3)
print(a[0, 1])  # In giá trị tại hàng 0, cột 1 của a (giá trị gốc là 2)
b[0, 0] = (
    77  # Thay đổi giá trị tại hàng 0, cột 0 của b; do b là view, a cũng bị thay đổi
)
print(
    a[0, 1]
)  # In giá trị tại hàng 0, cột 1 của a sau khi thay đổi (giá trị bây giờ là 77)

2
77


4. Explain the meaning of each command line and show the result of the
following code

In [13]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])  # Tạo mảng 3x4
row_r1 = a[1, :]  # Lấy hàng thứ 1 (hàng thứ hai) dưới dạng mảng 1 chiều
row_r2 = a[1:2, :]  # Lấy hàng thứ 1 dưới dạng mảng 2 chiều (slice vẫn giữ số chiều)
print(row_r1, row_r1.shape)  # In row_r1 và kích thước của nó (1D, shape=(4,))
print(row_r2, row_r2.shape)  # In row_r2 và kích thước của nó (2D, shape=(1,4))
col_r1 = a[:, 1]  # Lấy cột thứ 1 (cột thứ hai) dưới dạng mảng 1 chiều
col_r2 = a[:, 1:2]  # Lấy cột thứ 1 dưới dạng mảng 2 chiều (slice giữ số chiều)
print(col_r1, col_r1.shape)  # In col_r1 và kích thước của nó (1D, shape=(3,))
print(col_r2, col_r2.shape)  # In col_r2 và kích thước của nó (2D, shape=(3,1))

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


5. Explain the meaning of each command line and show the result of the
following code

In [12]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])  # Tạo mảng 3x2
print(
    a[[0, 1, 2], [0, 1, 0]]
)  # Chỉ định các chỉ số hàng và cột riêng lẻ để lấy phần tử: [a[0,0], a[1,1], a[2,0]]
print(
    np.array([a[0, 0], a[1, 1], a[2, 0]])
)  # Cách tương đương với dòng trên, tạo mảng từ các phần tử cụ thể
print(
    a[[0, 0], [1, 1]]
)  # Lấy phần tử a[0,1] hai lần theo chỉ số hàng và cột được chỉ định
print(
    np.array([a[0, 1], a[0, 1]])
)  # Cách tương đương với dòng trên, tạo mảng từ các phần tử cụ thể

[1 4 5]
[1 4 5]
[2 2]
[2 2]


6. Explain the meaning of each command line and show the result of the
following code

In [11]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])  # Tạo mảng 4x3
print(a)  # In mảng a ban đầu
b = np.array([0, 2, 0, 1])  # Mảng chỉ số cột cho từng hàng
print(
    a[np.arange(4), b]
)  # Lấy các phần tử theo hàng (0-3) và cột được chỉ định trong b: [a[0,0], a[1,2], a[2,0], a[3,1]]
a[np.arange(4), b] += 10  # Cộng 10 vào các phần tử được chọn theo hàng và cột
print(a)  # In mảng a sau khi cập nhật

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


7. Explain the meaning of each command line and show the result of the
following code

In [10]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])
bool_idx = (
    a > 2
)  # Tạo mảng Boolean cùng kích thước với a, True nếu phần tử > 2, False nếu <= 2
print(bool_idx)  # In mảng Boolean
print(a[bool_idx])  # Lấy tất cả các phần tử của a mà điều kiện > 2, trả về mảng 1 chiều
print(a[a > 2])  # Cách viết gọn tương đương, lấy các phần tử > 2 trực tiếp

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


8. Explain the meaning of each command line and show the result of the
following code

In [9]:
import numpy as np

x = np.array([1, 2])  # Tạo mảng 1 chiều với các số nguyên
print(x.dtype)  # In kiểu dữ liệu của mảng (int32 hoặc int64 tùy hệ thống)
x = np.array([1.0, 2.0])  # Tạo mảng 1 chiều với các số thực
print(x.dtype)  # In kiểu dữ liệu của mảng (float64)
x = np.array([1, 2], dtype=np.int64)  # Tạo mảng 1 chiều với kiểu dữ liệu int64 rõ ràng
print(x.dtype)  # In kiểu dữ liệu của mảng (int64)

int32
float64
int64


9. Explain the meaning of each command line and show the result of the
following code

In [8]:
import numpy as np

x = np.array([[1, 2], [3, 4]], dtype=np.float64)  # Tạo mảng 2x2 với kiểu float64
y = np.array([[5, 6], [7, 8]], dtype=np.float64)  # Tạo mảng 2x2 khác với kiểu float64
print(x + y)  # Cộng hai mảng theo phần tử
print(np.add(x, y))  # Cách gọi tương đương với x + y, dùng hàm add của NumPy
print(x - y)  # Trừ hai mảng theo phần tử
print(np.subtract(x, y))  # Cách gọi tương đương với x - y, dùng hàm subtract
print(x * y)  # Nhân hai mảng theo phần tử (element-wise multiplication)
print(np.multiply(x, y))  # Cách gọi tương đương với x * y, dùng hàm multiply
print(x / y)  # Chia hai mảng theo phần tử (element-wise division)
print(np.divide(x, y))  # Cách gọi tương đương với x / y, dùng hàm divide
print(np.sqrt(x))  # Tính căn bậc hai từng phần tử của mảng x

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


9. Explain the meaning of each command line and show the result of the
following code

In [7]:
import numpy as np

x = np.array([[1, 2], [3, 4]])  # Tạo mảng 2x2
y = np.array([[5, 6], [7, 8]])  # Tạo mảng 2x2 khác
v = np.array([9, 10])  # Tạo mảng 1 chiều (vector) độ dài 2
w = np.array([11, 12])  # Tạo mảng 1 chiều (vector) độ dài 2
print(v.dot(w))  # Tích vô hướng (dot product) giữa v và w: 9*11 + 10*12
print(np.dot(v, w))  # Cách gọi tương đương với v.dot(w)
print(x.dot(v))  # Nhân ma trận x với vector v
print(np.dot(x, v))  # Cách gọi tương đương với x.dot(v)
print(x.dot(y))  # Nhân ma trận x với ma trận y (ma trận 2x2 với 2x2)
print(np.dot(x, y))  # Cách gọi tương đương với x.dot(y)

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


10. Explain the meaning of each command line and show the result of the
following code

In [6]:
import numpy as np

x = np.array([[1, 2], [3, 4]])  # Tạo mảng 2x2
print(np.sum(x))  # Tính tổng tất cả phần tử của x
print(np.sum(x, axis=0))  # Tính tổng theo cột (axis=0)
print(np.sum(x, axis=1))  # Tính tổng theo hàng (axis=1)
x = np.array([[1, 2], [3, 4]])  # Tạo lại mảng 2x2
print(x)  # In mảng x
print(x.T)  # Chuyển vị ma trận x (hàng ↔ cột)
v = np.array([1, 2, 3])  # Tạo vector 1 chiều
print(v)  # In vector v
print(v.T)  # Chuyển vị của vector 1 chiều vẫn là chính nó (không thay đổi)

10
[4 6]
[3 7]
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


11. Explain the meaning of each command line and show the result of the
following code

In [5]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])  # Tạo mảng 4x3
v = np.array([1, 0, 1])  # Tạo vector 1x3
y = np.empty_like(x)  # Tạo mảng rỗng cùng kích thước và kiểu dữ liệu với x
for i in range(4):
    y[i, :] = x[i, :] + v  # Cộng vector v vào từng hàng của x và lưu vào y
print(y)  # In mảng y sau khi cộng

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


12. Explain the meaning of each command line and show the result of the
following code

In [4]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])  # Tạo mảng 4x3
v = np.array([1, 0, 1])  # Tạo vector 1x3
vv = np.tile(v, (4, 1))  # Nhân bản vector v thành ma trận 4x3, mỗi hàng là v
print(vv)  # In ma trận vv sau khi nhân bản
y = x + vv  # Cộng ma trận x với vv theo phần tử
print(y)  # In kết quả y

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


13. Explain the meaning of each command line and show the result of the
following code

In [3]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])  # Tạo mảng 4x3
v = np.array([1, 0, 1])  # Tạo vector 1x3
y = x + v  # Cộng vector v vào mỗi hàng của x nhờ broadcasting
print(y)  # In mảng y sau khi cộng

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


14. Explain the meaning of each command line and show the result of the
following code

In [2]:
import numpy as np

# Tính tích ngoài (outer product) của hai vector
v = np.array([1, 2, 3])  # Tạo vector v có shape (3,)
w = np.array([4, 5])  # Tạo vector w có shape (2,)
print(np.reshape(v, (3, 1)) * w)
# Chuyển v thành ma trận 3x1, nhân theo phần tử với w (broadcasting)
# Kết quả là ma trận 3x2:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]

x = np.array([[1, 2, 3], [4, 5, 6]])  # Tạo ma trận 2x3
print(x + v)
# Cộng vector v vào từng hàng của x nhờ broadcasting
# Kết quả:
# [[2 4 6]
#  [5 7 9]]

print((x.T + w).T)
# Chuyển vị x -> shape (3x2), cộng vector w theo cột (broadcasting), rồi chuyển vị lại
# Kết quả tương tự:
# [[5 7 6]
#  [8 10 7]] ???

print(x + np.reshape(w, (2, 1)))
# Chuyển w thành ma trận 2x1, cộng với x theo hàng
# Kết quả:
# [[5 6 7]
#  [9 10 11]]

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]


15. Explain the meaning of each command line and show the result of the
following code

In [1]:
import numpy as np

v = np.array([1, 2, 3])  # Tạo vector 1 chiều v với các phần tử [1,2,3]
w = np.array([4, 5])  # Tạo vector 1 chiều w với các phần tử [4,5]

print(
    np.reshape(v, (3, 1)) * w
)  # Chuyển v thành ma trận 3x1, nhân với w (broadcasting)


x = np.array([[1, 2, 3], [4, 5, 6]])  # Tạo ma trận 2x3
print(x + v)  # Cộng vector v vào từng hàng của x nhờ broadcasting


print(
    (x.T + w).T
)  # Chuyển vị x -> shape (3x2), cộng vector w theo cột (broadcasting), rồi chuyển vị lại


print(
    x + np.reshape(w, (2, 1))
)  # Chuyển w thành ma trận 2x1, cộng với x theo hàng (broadcasting)


print(x * 2)  # Nhân tất cả phần tử của x với 2

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
